"""
crawlers/hypefly/discovery.py — Discover all HypeFly product slugs via sitemap.

Why sitemap over HTML crawling?
  Sitemaps are generated by the CMS specifically for bots (Google, crawlers).
  They're structured XML, stable, and contain every published URL.
  Parsing a sitemap is O(1) complexity — one request, all URLs.
  HTML crawling requires paginating through collection pages, handling
  infinite scroll or load-more buttons, and is fragile to layout changes.

HypeFly sitemap structure (standard Next.js/Strapi sitemap):
  https://hypefly.co.in/sitemap.xml
  May be an index pointing to sub-sitemaps:
    https://hypefly.co.in/server-sitemap.xml  (dynamic pages: products)
    https://hypefly.co.in/sitemap-0.xml        (static pages)

We only care about product URLs matching the pattern:
  https://hypefly.co.in/products/{slug}

Strategy:
  1. Fetch sitemap.xml
  2. If it's a sitemap index, fetch each sub-sitemap
  3. Filter URLs matching /products/ pattern
  4. Extract slug from each URL
"""

import re
from crawlers.base.fetcher import BaseFetcher
from config import HYPEFLY_BASE_URL

# Matches product URLs: https://hypefly.co.in/products/some-slug
PRODUCT_URL_PATTERN = re.compile(
    r"https://hypefly\.co\.in/products/([a-z0-9\-]+)"
)


class HypeflyDiscovery:

    def __init__(self, fetcher: BaseFetcher):
        # Discovery reuses the same fetcher instance as product fetching.
        # This keeps rate limiting consistent — one fetcher, one delay counter.
        self.fetcher = fetcher

    def get_all_slugs(self) -> list[str]:
        """
        Return all product slugs found in HypeFly's sitemap.

        Handles both flat sitemaps and sitemap index files.
        """
        print(f"[hypefly:discovery] Fetching sitemap: {HYPEFLY_BASE_URL}/sitemap.xml")
        response = self.fetcher.get(f"{HYPEFLY_BASE_URL}/sitemap.xml")
        xml = response.text

        # Check if this is a sitemap index (contains <sitemapindex>)
        if "<sitemapindex" in xml:
            print("[hypefly:discovery] Found sitemap index — fetching sub-sitemaps...")
            return self._parse_sitemap_index(xml)
        else:
            return self._extract_slugs_from_xml(xml)

    def _parse_sitemap_index(self, index_xml: str) -> list[str]:
        """
        A sitemap index lists other sitemaps. Fetch each and collect slugs.

        Example index entry:
          <sitemap>
            <loc>https://hypefly.co.in/server-sitemap.xml</loc>
          </sitemap>
        """
        # Extract all sitemap URLs from the index
        sitemap_urls = re.findall(r"<loc>(https://[^<]+\.xml[^<]*)</loc>", index_xml)
        print(f"[hypefly:discovery] Found {len(sitemap_urls)} sub-sitemaps")

        all_slugs = []
        for url in sitemap_urls:
            print(f"[hypefly:discovery] Fetching sub-sitemap: {url}")
            try:
                response = self.fetcher.get(url)
                slugs = self._extract_slugs_from_xml(response.text)
                print(f"[hypefly:discovery]   → {len(slugs)} product URLs")
                all_slugs.extend(slugs)
            except Exception as e:
                print(f"[hypefly:discovery] ⚠ Failed to fetch {url}: {e}")

        return all_slugs

    def _extract_slugs_from_xml(self, xml: str) -> list[str]:
        """
        Extract product slugs from a sitemap XML string.

        We match only /products/ URLs and ignore:
          - /collections/
          - /pages/
          - /team/
          - homepage
        """
        # Find all <loc> values
        all_locs = re.findall(r"<loc>([^<]+)</loc>", xml)

        slugs = []
        for loc in all_locs:
            match = PRODUCT_URL_PATTERN.match(loc.strip())
            if match:
                slugs.append(match.group(1))

        return slugs